export const FETCH_DATA_SUCCEEDED = "FETCH_DATA_SUCCEEDED";
export const FETCH_DATA_FAILED = "FETCH_DATA_FAILED";
export const FETCH_DATA_REQUESTED = "FETCH_DATA_REQUESTED";

export const FETCH_MORE_SUCCEEDED = "FETCH_MORE_SUCCEEDED";